# pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-ast
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer

# add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma

# black
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      args: [
          '--line-length', '100',
          '--skip-string-normalization',
      ]

# pycln
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
    -   id: pycln
        args: [
            'all',
        ]

# isort
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [
            '--line_length', '100',
            '--multi_line_output', '3',
            '--force_grid_wrap', '0',
            '--include_trailing_comma',
            '--use_parentheses',
            '--ensure_newline_before_comments',
        ]

# pydocstyle
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        additional_dependencies: ['toml']
        args: [
            '--convention', 'google',
            '--add-ignore', 'D102,D103,D104,D105,D106,D107',
        ]
