# pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-ast
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer

# add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma

# black
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      args: [
          '--line-length', '100',
          '--skip-string-normalization',
      ]

# flake8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

# pylint
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        args: [
            '--disable', 'all',
            '--enable', 'unused-import',
        ]

# isort
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
    -   id: isort

# pydocstyle
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        additional_dependencies: ['toml']
        args: [
            '--convention', 'google',
            '--add-ignore', 'D102,D103,D104,D105,D106,D107',
        ]
