# pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer

# black
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black

# flake8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

# pylint
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        args: [--disable=all, --enable=unused-import]

# interrogate
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate

# isort
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
    -   id: isort

# add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
