# pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-ast
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer

# add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma

# black
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      args: ['--config', 'pyproject.toml']

# pycln
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
    -   id: pycln
        args: ['--config', 'pyproject.toml']

# isort
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: ['--settings-path', 'pyproject.toml']

# pydocstyle
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.2.1'
    hooks:
    -   id: pydocstyle
        additional_dependencies: ['toml']
        args: ['--config', 'pyproject.toml']

# mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: ['--config-file',  'pyproject.toml']
