stages:

  convert_sly_to_int:
    cmd:
    - rm -rf data/interim || true
    - python src/data/convert_sly_to_int.py
    deps:
    - src/data/convert_sly_to_int.py
    - src/data/utils_sly.py
    - configs/convert_sly_to_int.yaml
    - data/sly
    outs:
    - data/interim/img
    - data/interim/metadata.xlsx

  segment_lungs:
    cmd:
    - rm -rf data/interim_lung_seg || true
    - python src/segment_lungs.py
    deps:
    - src/segment_lungs.py
    - src/models/lung_segmenter.py
    - configs/segment_lungs.yaml
    - data/interim/img
    outs:
    - data/interim_lung_seg

  fuse_maps:
    cmd:
    - rm -rf data/interim_fused || true
    - python src/fuse_maps.py
    deps:
    - src/fuse_maps.py
    - src/models/map_fuser.py
    - src/models/mask_processor.py
    - src/data/utils_sly.py
    - configs/fuse_maps.yaml
    - data/interim_lung_seg
    outs:
    - data/interim_fused/map
    - data/interim_fused/mask
    - data/interim_fused/metadata.xlsx

  convert_int_to_final:
    cmd:
    - rm -rf data/final || true
    - python src/data/convert_int_to_final.py
    deps:
    - src/data/convert_int_to_final.py
    - src/data/utils_final.py
    - configs/convert_int_to_final.yaml
    - data/interim/img
    - data/interim/metadata.xlsx
    - data/interim_fused/metadata.xlsx
    outs:
    - data/final/img
    - data/final/metadata.xlsx
