defaults:
- main
- _self_

dataset_dir: data/interim
# figure name: (horizontal, vertical)
box_extension: {Cephalization: [0, 0], Artery: [0, 0], Heart: [0, 0], Kerley: [0, 0], Bronchus: [0, 0], Effusion: [0, 0], Bat: [0, 0], Infiltrate: [0, 0], Cuffing: [0, 0]}
exclude_classes: []
train_size: 0.80
seed: 11
save_dir: data/coco
