defaults:
- main
- _self_

dataset_dir: data/interim
dataset_dir_fused: data/interim_fused
# [width, height]; if list is empty, no resize is used
output_size: [1664, 2048]
# figure name: [left (x1), top (y1), right (x2), bottom (y2)]
box_extension:
  Cephalization: [0, 0, 0, 0]
  Artery: [0, 0, 0, 0]
  Heart: [0, 0, 0, 0]
  Kerley: [0, 5, 0, 5]
  Bronchus: [0, 0, 0, 0]
  Effusion: [0, 0, 0, 0]
  Bat: [0, 0, 0, 0]
  Infiltrate: [0, 0, 0, 0]
  Cuffing: [0, 0, 0, 0]
  Lungs: [50, 50, 50, 150]
save_dir: data/final
