defaults:
- main
- _self_

dataset_dir: data/interim
dataset_dir_fused: data/interim_fused
# [width, height]; if list is empty, no resize is used
output_size: [1664, 2048]
# figure name: (horizontal, vertical)
box_extension:
  Cephalization: [0, 0]
  Artery: [0, 0]
  Heart: [0, 0]
  Kerley: [0, 0]
  Bronchus: [0, 0]
  Effusion: [0, 0]
  Bat: [0, 0]
  Infiltrate: [0, 0]
  Cuffing: [0, 0]
  Lungs: [0, 0]
excluded_features: []
train_size: 0.80
seed: 11
save_dir: data/coco
