defaults:
- main
- _self_

dataset_dir: data/interim
dataset_dir_fused: data/interim_fused
enable_cropping: true
enable_resizing: true
enable_padding: true
output_size: [1536, 1536]       # output_size is only used if enable_cropping = true
box_extension:                  # feature name: [left (x1), top (y1), right (x2), bottom (y2)]
  Cephalization: [0, 0, 0, 0]
  Artery: [0, 0, 0, 0]
  Heart: [0, 0, 0, 0]
  Kerley: [0, 5, 0, 5]
  Bronchus: [0, 0, 0, 0]
  Effusion: [0, 0, 0, 0]
  Bat: [0, 0, 0, 0]
  Infiltrate: [0, 0, 0, 0]
  Cuffing: [0, 0, 0, 0]
  Lungs: [50, 50, 50, 150]
save_dir: data/final
