defaults:
- main
- _self_

gt_path: data/coco/test/labels.xlsx
pred_path: data/coco/test/predictions.xlsx
iou_range: [0.4, 0.45]
iou_step: 0.01
conf_range: [0.6, 0.6]
conf_step: 0.01
# List of features: Cephalization, Artery, Heart, Kerley, Bronchus, Effusion, Bat, Infiltrate, Cuffing
exclude_features: []
save_dir: eval
