defaults:
- main
- _self_

gt_path: data/final/metadata.xlsx
pred_path: data/interim_predict/metadata.xlsx
iou_threshold: 0.5
conf_range: [0.0, 1.0]
conf_step: 0.05
# List of features: Cephalization, Artery, Heart, Kerley, Bronchus, Effusion, Bat, Infiltrate, Cuffing, Lungs
exclude_features: [Heart, Lungs, Artery, Bronchus]
save_dir: eval
