defaults:
- main
- _self_

data_dir: data/interim
save_dir: data/interim_predict/SABL

# Segmentation settings
seg_model_dirs:
- models/lung_segmentation/DeepLabV3
- models/lung_segmentation/FPN
- models/lung_segmentation/MAnet

# Detection settings
det_model_dirs:
- models/feature_detection/SABL/cephalization
- models/feature_detection/SABL/bat
- models/feature_detection/SABL/effusion
- models/feature_detection/SABL/infiltrate
- models/feature_detection/SABL/kerley
img_size: [1536, 1536]
lung_extension: [50, 50, 50, 150]

# Non-Maximum Suppression settings
nms_method: soft      # soft or standard
iou_threshold: 0.5
conf_thresholds:
  Cephalization: 0.0
  Artery: 0.0
  Heart: 0.0
  Kerley: 0.0
  Bronchus: 0.0
  Effusion: 0.0
  Bat: 0.0
  Infiltrate: 0.0
  Cuffing: 0.0
  Lungs: 0.0
