defaults:
- main
- _self_

data_dir: data/demo/input
save_dir: data/demo/output

# Segmentation settings
seg_model_dirs:
- models/lung_segmentation/DeepLabV3
- models/lung_segmentation/FPN
- models/lung_segmentation/MAnet

# Detection settings
det_model_dirs:
- models/feature_detection/SABL/cephalization
- models/feature_detection/SABL/bat
- models/feature_detection/SABL/effusion
- models/feature_detection/SABL/infiltrate
- models/feature_detection/SABL/kerley
img_size: [1536, 1536]
lung_extension: [50, 50, 50, 150]

# Non-Maximum Suppression settings
nms_method: soft      # soft or standard
iou_threshold: 0.5
conf_thresholds:
  Cephalization: 0.37
  Kerley: 0.53
  Effusion: 0.77
  Bat: 0.48
  Infiltrate: 0.38
