defaults:
- main
- _self_

img_dir: data/interim
model_names: ['MAnet', 'DeepLabV3', 'Unet++']    # Unet, Unet++, DeepLabV3, DeepLabV3+, FPN, Linknet, PSPNet, PAN, MAnet
model_dirs: models/lung_segmentation
save_dir: data/interim_lungs
