defaults:
- main
- _self_

gt_path: data/final/metadata.xlsx
pred_path: data/interim_predict/metadata.xlsx
conf_threshold: 0.01
# List of features: Cephalization, Artery, Heart, Kerley, Bronchus, Effusion, Bat, Infiltrate, Cuffing
exclude_features: [Heart, Artery, Bronchus]
