defaults:
- main
- _self_

gt_path: data/interim/metadata.xlsx
pred_path: data/interim_predict/metadata.xlsx
iou_threshold: 0.5
conf_threshold: 0.5
# List of features: Cephalization, Artery, Heart, Kerley, Bronchus, Effusion, Bat, Infiltrate, Cuffing
exclude_features: [Lungs, Heart, Artery, Bronchus]
